version: '3.6'

services:
  www.igorleonovich.com:
      image: nginx
      restart: always
      volumes:
        - "./:/usr/share/nginx/html"
      environment:
        - VIRTUAL_HOST=www.igorleonovich.com
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=www.igorleonovich.com
        - LETSENCRYPT_EMAIL=mail@igorleonovich.com

  igorleonovich.com:
    image: cusspvz/redirect
    restart: always
    environment:
      - VIRTUAL_HOST=igorleonovich.com
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - LETSENCRYPT_HOST=igorleonovich.com
      - REDIRECT=https://www.igorleonovich.com
      - WORKER_CONNECTIONS=1024

networks:
  default:
    external:
      name: nginx-proxy
